Closes #18 and #5
mumuki/mumuki-qsim-runner pull request #19
Opened 2017-02-10 04:45 UTC by Charlyzzz

2017-02-10 13:58 UTC, faloi commented
The `closes #...` should be in the description, it doesn't work if you put in the title.

2017-02-10 14:10 UTC, faloi requested changes
Once this is ready and before it's deployed, you should prepare a migration to adapt existing exercises to the new format. 

There is a rake task on bibliotheca that will help you with the migration, see: https://github.com/mumuki/mumuki-bibliotheca-api/blob/master/migrations/migrate_convert_exercise_layout_editors.rb.

2017-02-10 14:10 UTC, faloi commented on lib/test_hook.rb
> +    fields.map do |key, value|
Since you don't care about the result of this, you should use `each` instead of `map`.

2017-02-10 14:10 UTC, faloi commented on lib/test_hook.rb
> +      classified_fields.deep_merge!(records: { key => value }) if record?(field)
You can avoid this repeated logic by creating a function that takes the key and returns its category. Then, you can do something like:

```ruby
kind = classify field 
unless kind == :unknown
  classified_fields[kind].merge! { key => value }
end
```

2017-02-14 17:36 UTC, Charlyzzz commented on lib/test_hook.rb
> +      classified_fields.deep_merge!(records: { key => value }) if record?(field)
If the kind doesn´t exists it is nil, so it won´t look so clean as your example. I'll see what I can do

2017-02-14 20:05 UTC, faloi approved these changes

2017-02-14 20:05 UTC, merged