Memory check postcondition#17
mumuki/mumuki-qsim-runner pull request #23
Opened 2017-02-23 04:35 UTC by Charlyzzz

2017-03-02 18:40 UTC, flbulgarelli commented on spec/data/multiple_checks.rb
> +
Don't use fixture objects. Place them directly in the test

2017-03-03 19:37 UTC, faloi requested changes

2017-03-03 19:37 UTC, faloi commented on lib/checker.rb
>      def check_equal(result, records)
The second parameter are not `records` anymore, since they also can include flags, memory positions, etc. We should change that name.

2017-03-03 19:37 UTC, faloi commented on lib/checker.rb
> +        actual = result[:records].merge(memory).fetch(record, '0000')
This is quite ugly, the `fetch` is heavily dependant on the current output QSim has. We should have our own internal representation of the QSim machine and use it across all the component.

You have already solved the parsing issue, now please reify the machine so we don't have to do these kind of things everytime we want to get the value of a memory cell.

2017-10-31 15:32 UTC, fedescarpa commented
Dado que no tuvo actividad voy a proceder a cerrarlo

2017-10-31 15:32 UTC, closed without merging